# Databricks Apps Configuration
# This file configures the deployment of the Healthcare Provider Directory app

command: ["python", "wsgi.py", "--port=8081"]

env:
  - name: PYTHONPATH
    value: "/app/python/source_code:/app/python/source_code"
  - name: FLASK_APP
    value: app.py
  - name: FLASK_ENV
    value: production
  - name: ENABLE_DATABRICKS
    value: "true"
  
  # Databricks connection settings (will be configured in Databricks Apps UI)
  - name: DATABRICKS_HOST
    value: ""  # Set in Databricks Apps UI or use secrets
  - name: DATABRICKS_TOKEN
    value: ""  # Use Databricks secrets or set in UI
  - name: DATABRICKS_HTTP_PATH
    value: ""  # SQL Warehouse HTTP path
  
  # Catalog and schema configuration
  - name: DATABRICKS_CATALOGS
    value: "databricks_poc"
  - name: DATABRICKS_SCHEMAS
    value: "default"
  - name: DATABRICKS_TABLE_PATTERN
    value: "batch_process_output,csv_upload_details"
  - name: DATABRICKS_CACHE_DURATION
    value: "5"
  
  # Flask secret key (generate a secure key for production)
  - name: FLASK_SECRET_KEY
    value: ""  # Set a secure random key

# Resource limits (optional)
resources:
  limits:
    memory: "2Gi"
    cpu: "1000m"
  requests:
    memory: "1Gi"
    cpu: "500m"
